"""
client.py - the only place your app talks to a model.

DO NOT EDIT THIS FILE. The marking harness checks it is unchanged.

Everything this file needs comes from three environment variables in .env:

    LLM_API_KEY     your key, from any provider
    LLM_BASE_URL    an OpenAI-compatible endpoint, or local://stub
    LLM_MODEL       a model name, or stub:<mode> when using the stub

Changing provider is three lines in .env and nothing else.
"""

import os

try:
    from dotenv import load_dotenv
    load_dotenv()          # does not override variables already set
except ImportError:
    pass


def get_client():
    """Return a client. A real one, or the local stub."""
    base_url = os.getenv("LLM_BASE_URL", "")

    if base_url.startswith("local://stub"):
        from stub_client import StubClient
        return StubClient(os.getenv("LLM_MODEL", "stub:ok"))

    from openai import OpenAI
    return OpenAI(
        api_key=os.getenv("LLM_API_KEY"),
        base_url=base_url or None,
    )


def get_model() -> str:
    """Return the model name from the environment."""
    return os.getenv("LLM_MODEL", "")
