"""
stub_client.py - a local, offline fake model.

Supplied with Lab 5. This is the Lab 4 stub with two modes added.
DO NOT EDIT THIS FILE.
The marking harness uses its own copy of this exact file. If you change
yours, your acceptance checks stop meaning anything.

WHAT IT IS
    A fake model that never touches the network, needs no API key, costs
    nothing, and returns the same thing every time. Its job is to let you
    trigger failures on purpose. You cannot ask a real model to return
    malformed JSON on demand; you can ask this one.

HOW TO USE IT
    In .env:
        LLM_BASE_URL=local://stub
        LLM_MODEL=stub:ok

    Change stub:ok to any mode below and run your program again.

THE TEN MODES
    stub:ok         your samples/valid_response.json, exactly as written
    stub:fenced     the same JSON wrapped in ```json ... ``` fences
    stub:preamble   the same JSON after a chatty sentence
    stub:malformed  the same JSON with a trailing comma (does not parse)
    stub:badshape   your samples/invalid_response.json, exactly as written
    stub:empty      an empty string
    stub:refused    a refusal message, in prose
    stub:error      raises StubError before returning anything

    New in Lab 5. These two exist so that retry behaviour can be tested:

    stub:flaky      raises StubError on the FIRST call of the process, then
                    returns your valid_response.json on every call after it.
                    A program that retries an error ends ok. One that does
                    not ends error.
    stub:ratelimit  raises StubRateLimitError on every call, carrying
                    status_code 429 and retry_after = 1 second. Nothing you
                    do makes it succeed. It exists to prove that your retry
                    loop has a cap and then gives up cleanly.

    The counter behind stub:flaky lives in this module, so it resets every
    time you start the program. One run of main.py sees one failure.

TWO FILES YOU MUST CREATE
    samples/valid_response.json
        One reply, in YOUR schema, that your program must accept.
    samples/invalid_response.json
        One reply that is valid JSON but that your validation must REJECT.

    The stub does not know or care what shape you chose. That is the point:
    everyone's schema is different, and the same stub tests all of them.
"""

import json
import os
from pathlib import Path


class StubError(RuntimeError):
    """Raised by stub:error. Stands in for a network or provider failure."""


class StubRateLimitError(StubError):
    """Raised by stub:ratelimit. Stands in for an HTTP 429 from a provider.

    It is a StubError, so code that already catches StubError keeps working.
    Catch this one separately if you want to honour retry_after.
    """

    def __init__(self, message: str, retry_after: float = 1.0):
        super().__init__(message)
        self.status_code = 429
        self.retry_after = retry_after


_REFUSAL = (
    "I'm sorry, but I can't help with that. I'm not able to generate "
    "questions on this topic."
)

_PREAMBLE = "Sure! Here's the JSON you asked for:\n\n"

_CALL_LOG = ".stub_calls.log"

# How many times each mode has been called in THIS process. Reset on every
# run of your program, which is what makes stub:flaky fail exactly once.
_CALLS: dict[str, int] = {}


def _nth_call(mode: str) -> int:
    _CALLS[mode] = _CALLS.get(mode, 0) + 1
    return _CALLS[mode]


# --------------------------------------------------------------------------
# Loading your samples
# --------------------------------------------------------------------------

def _samples_dir() -> Path:
    return Path(os.getenv("STUB_SAMPLES_DIR", "samples"))


def _load_sample(name: str) -> str:
    path = _samples_dir() / name
    if not path.exists():
        raise StubError(
            f"{path} not found.\n"
            f"The stub returns YOUR sample replies, so you have to write them.\n"
            f"Create {path} containing one reply in your own schema.\n"
            f"See the comment at the top of stub_client.py."
        )
    text = path.read_text(encoding="utf-8").strip()
    try:
        json.loads(text)
    except json.JSONDecodeError as exc:
        raise StubError(
            f"{path} is not valid JSON ({exc}).\n"
            f"Both sample files must be valid JSON. "
            f"invalid_response.json is meant to be valid JSON that your "
            f"VALIDATION rejects, not text that json.loads rejects."
        ) from exc
    return text


def _break_json(text: str) -> str:
    """Insert a trailing comma before the last closing bracket."""
    i = max(text.rfind("}"), text.rfind("]"))
    if i == -1:
        return text + ","
    return text[:i] + "," + text[i:]


def _content_for(mode: str) -> str:
    if mode == "ok":
        return _load_sample("valid_response.json")
    if mode == "fenced":
        return "```json\n" + _load_sample("valid_response.json") + "\n```"
    if mode == "preamble":
        return _PREAMBLE + _load_sample("valid_response.json")
    if mode == "malformed":
        return _break_json(_load_sample("valid_response.json"))
    if mode == "badshape":
        return _load_sample("invalid_response.json")
    if mode == "empty":
        return ""
    if mode == "refused":
        return _REFUSAL
    if mode == "error":
        raise StubError("stub:error - simulated provider failure")
    if mode == "flaky":
        if _nth_call("flaky") == 1:
            raise StubError(
                "stub:flaky - simulated transient failure on the first call"
            )
        return _load_sample("valid_response.json")
    if mode == "ratelimit":
        _nth_call("ratelimit")
        raise StubRateLimitError(
            "stub:ratelimit - 429 Too Many Requests (simulated)",
            retry_after=1.0,
        )
    raise StubError(
        f"Unknown stub mode: {mode!r}. "
        f"LLM_MODEL must be one of: stub:ok, stub:fenced, stub:preamble, "
        f"stub:malformed, stub:badshape, stub:empty, stub:refused, "
        f"stub:error, stub:flaky, stub:ratelimit"
    )


# --------------------------------------------------------------------------
# A response object shaped like the one the OpenAI SDK returns
# --------------------------------------------------------------------------

class _Message:
    def __init__(self, content: str):
        self.role = "assistant"
        self.content = content
        self.tool_calls = None


class _Choice:
    def __init__(self, content: str):
        self.index = 0
        self.message = _Message(content)
        self.finish_reason = "stop"


class _Usage:
    def __init__(self, prompt_tokens: int, completion_tokens: int):
        self.prompt_tokens = prompt_tokens
        self.completion_tokens = completion_tokens
        self.total_tokens = prompt_tokens + completion_tokens


class _Completion:
    def __init__(self, content: str, model: str, prompt_chars: int):
        self.id = "stub-completion"
        self.model = model
        self.choices = [_Choice(content)]
        self.usage = _Usage(max(1, prompt_chars // 4), max(1, len(content) // 4))


# --------------------------------------------------------------------------
# The client
# --------------------------------------------------------------------------

class _Completions:
    def __init__(self, model: str):
        self._model = model

    def create(self, model=None, messages=None, **kwargs):
        """Mimics client.chat.completions.create(...).

        Extra keyword arguments such as response_format or temperature are
        accepted and ignored, the way a low-tier free model often does.
        """
        requested = model or self._model or "stub:ok"
        if not str(requested).startswith("stub:"):
            raise StubError(
                f"LLM_BASE_URL is local://stub but LLM_MODEL is {requested!r}. "
                f"When using the stub, LLM_MODEL must start with 'stub:'."
            )
        mode = str(requested).split(":", 1)[1].strip()

        prompt_chars = sum(
            len(str(m.get("content", ""))) for m in (messages or [])
        )
        try:
            with open(_CALL_LOG, "a", encoding="utf-8") as fh:
                fh.write(f"{requested}\t{prompt_chars}\n")
        except OSError:
            pass

        content = _content_for(mode)
        return _Completion(content, requested, prompt_chars)


class _Chat:
    def __init__(self, model: str):
        self.completions = _Completions(model)


class StubClient:
    """Drop-in stand-in for the OpenAI client, for the calls this course makes."""

    def __init__(self, model: str = "stub:ok"):
        self.model = model
        self.chat = _Chat(model)
